accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^entrar/$', views.meu_login, name='login'),
    url(r'^sair/$', auth_views.logout, {'next_page': 'accounts:login'}, name='logout'),
    url(r'^cadastro/$', views.cadastro, name='cadastro'),
    url(r'^cadastro/(?P<key>\w*)/$', views.cadastro, name='cadastro'),
    url(r'^cadastro/novo-perfil/$', views.PerfilCreateView.as_view(), name='novo_perfil'),
    url(r'^editar/(?P<pk>\d+)/$', views.UsuarioUpdateView.as_view(), name='editar'),
    url(r'^(?P<pk>\d+)/$', views.UsuarioUpdateApiView.as_view(), name='editar_api'),
    url(r'^editar-senha/$', views.editar_senha, name='editar_senha'),
    url(r'^nova-senha/$', views.reset_senha, name='reset_senha'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)/$', views.reset_senha_confirm, name='reset_senha_confirm'),
    url(r'^certificado/orientador/(?P<pk>\d+)/$', views.CertificadoOrientadorPDFView.as_view(), name='certificado_orientador'),
    url(r'^certificado/avaliador/(?P<pk>\d+)/(?P<user_id>\d+)/$', views.CertificadoAvaliadorPDFView.as_view(), name='certificado_avaliador'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

core/urls.py
from django.conf.urls import include, url
from . import  views


urlpatterns = [
    # Examples:
    url(r'^$', views.home, name='home'),
    url(r'^bancas_pendentes/$', views.banca_pendente, name='bancas_pendentes'),
    url(r'^agendamentos_pendentes/$', views.agendamento_pendente, name='agendamentos_pendentes'),
    url(r'^defesas_confirmadas/$', views.defesas_confirmadas, name='defesas_confirmadas'),
]

defesa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^trabalhos/', include('trabalhos.urls', namespace='trabalhos')),
    url(r'^email/', include('mensagem.urls', namespace='mensagem')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trabalhos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Examples:
    url(r'^cadastrar-trabalho/novo$', views.cadastrar_trabalho, name='cadastrar_trabalho'),
    url(r'^detalhe/(?P<pk>\d+)/$', views.detalhe, name='detalhe'),
    url(r'^editar/(?P<pk>\d+)/$', views.TrabalhoUpdateView.as_view(), name='editar'),
    url(r'^(?P<pk>\d+)/$', views.TrabalhoDetail.as_view(), name='deletar'),
    url(r'^agendamento/novo/(?P<pk>\d+)/$', views.defesatrabalho, name='cadastrar_agendamento_defesa'),
    url(r'^banca-trabalho/(?P<pk>\d+)/$', views.banca_trabalho, name='banca_trabalho'),
    url(r'^deletar-agendamento/(?P<pk>\d+)/$', views.AgendamentoDetail.as_view(), name='deletar_agendamento'),
    url(r'^detalhe-agendamento/(?P<pk>\d+)/$', views.AgendamentoDetail.as_view(), name='detalhe_agendamento'),
]

core/models.py
from django.db import models
# Create your models here.

class Teste(models.Model):
    teste = models.CharField('Teste', max_length=30)


    class Meta:
        verbose_name = 'Teste'
        verbose_name_plural = 'Teste'

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from trabalhos.models import Trabalhos, DefesaTrabalho

@login_required
def home(request):
	template_nameHome = 'core/home.html'
	return render(request, template_nameHome)

def banca_pendente(request):
	trabalhos = Trabalhos.objects.all().filter(defesatrabalho__isnull=True)
	defesas = DefesaTrabalho.objects.all()
	list = []
	for defesa in defesas:
		avaliadores = defesa.trabalho.banca.all().exclude(bancatrabalho__status__contains='negado')
		lista = []
		for avaliador in avaliadores:
			lista.append(avaliador.name)

		defesas_dic = {
			'id': defesa.id,
			'local': defesa.local,
			'data': defesa.data,
			'hora': defesa.hora,
			'trabalho': defesa.trabalho,
			'banca': lista,
			'status': defesa.status,
		}
		list.append(defesas_dic)
		contextBanca = {"trabalhos": trabalhos, "defesas": list}
		template_nameBanca = 'core/banca_pendente.html'
	return  render(request, template_nameBanca, contextBanca)

def agendamento_pendente(request):
	trabalhos = Trabalhos.objects.all().filter(defesatrabalho__isnull=True)
	defesas = DefesaTrabalho.objects.all()
	list = []
	for defesa in defesas:
		avaliadores = defesa.trabalho.banca.all().exclude(bancatrabalho__status__contains='negado')
		lista = []
		for avaliador in avaliadores:
			lista.append(avaliador.name)

		defesas_dic = {
			'id': defesa.id,
			'local': defesa.local,
			'data': defesa.data,
			'hora': defesa.hora,
			'trabalho': defesa.trabalho,
			'banca': lista,
			'status': defesa.status,
		}
		list.append(defesas_dic)
		contextAgendamento = {"trabalhos": trabalhos, "defesas": list}
		template_nameAgendamento = 'core/agendamento_pendente.html'
	return  render(request, template_nameAgendamento, contextAgendamento)

def defesas_confirmadas(request):
	trabalhos = Trabalhos.objects.all().filter(defesatrabalho__isnull=True)
	defesas = DefesaTrabalho.objects.all()
	list = []
	for defesa in defesas:
		avaliadores = defesa.trabalho.banca.all().exclude(bancatrabalho__status__contains='negado')
		lista = []
		for avaliador in avaliadores:
			lista.append(avaliador.name)

		defesas_dic = {
			'id': defesa.id,
			'local': defesa.local,
			'data': defesa.data,
			'hora': defesa.hora,
			'trabalho': defesa.trabalho,
			'banca': lista,
			'status': defesa.status,
		}
		list.append(defesas_dic)
		contextDefesas = {"trabalhos": trabalhos, "defesas": list}
		template_nameDefesa = 'core/defesas_confirmadas.html'
	return  render(request, template_nameDefesa, contextDefesas)

defesa/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from defesa.trabalhos.models import Trabalhos

@login_required
def home(request):
	trabalhos = Trabalhos.objects.all()
	template_name = 'home.html'
	context = {"trabalhos": trabalhos}
	return render(request, template_name, context)

defesa/core/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Defesas Ufba</title>


    <link rel="stylesheet" type="text/css" href="{% static 'core/font-awesome/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'core/css/local.css' %}" />
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
     
    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
             
    <script type="text/javascript" src="{% static 'core/js/jquery-1.10.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/js/local.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js"></script>

    <!-- you need to include the shieldui css and js assets in order for the charts to work -->
    <link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light-bootstrap/all.min.css" />
    <link id="gridcss" rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/dark-bootstrap/all.min.css" />

    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
    <script type="text/javascript" src="http://www.prepbootstrap.com/Content/js/gridData.js"></script>
</head>
<body>
    <div id="wrapper">
          <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Menu</a>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul id="active" class="nav navbar-nav side-nav">
                    <li class="selected"><a href="{% url 'core:home' %}"><i class="fa fa-bullseye"></i> Home</a></li>
                    <li><a href="portfolio.html"><i class="fa fa-tasks"></i> Trabalhos</a></li>
                    <!--<li><a class="text-primary" href="blog.html"><i class="fa fa-globe"></i> Trabalhos</a></li>-->
                    <!--<li><a href="signup.html"><i class="fa fa-list-ol"></i> SignUp</a></li>-->
                    <!--<li><a href="register.html"><i class="fa fa-font"></i> Register</a></li>-->
                    <!--<li><a href="timeline.html"><i class="fa fa-font"></i> Timeline</a></li>-->
                    <li><a href="{% url 'trabalhos:cadastrar_trabalho' %}"><i class="fa fa-list-ol"></i> Cadastrar Trabalho</a></li>
                    {% if "Professor" == user.perfil.descricao %}
                        <li><a href="#"><i class="fa fa-list-ol"></i> Escolher Banca</a></li>
                        <li><a href="#"><i class="fa fa-list-ol"></i> Agendar</a></li>
                    {% endif %}
                   <!-- <li><a href="typography.html"><i class="fa fa-font"></i> Typography</a></li>
                    <li><a href="bootstrap-elements.html"><i class="fa fa-list-ul"></i> Bootstrap Elements</a></li>
                    <li><a href="bootstrap-grid.html"><i class="fa fa-table"></i> Bootstrap Grid</a></li>-->
                </ul>
                <ul class="nav navbar-nav navbar-right navbar-user">
                    <li class="dropdown messages-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> Messages <span class="badge">2</span> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">2 New Messages</li>
                            <li class="message-preview">
                                <a href="#">
                                    <span class="avatar"><i class="fa fa-bell"></i></span>
                                    <span class="message">Security alert</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li class="message-preview">
                                <a href="#">
                                    <span class="avatar"><i class="fa fa-bell"></i></span>
                                    <span class="message">Security alert</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Mais Mensagens <span class="badge">2</span></a></li>
                        </ul>
                    </li>
                    <li class="dropdown user-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{user.name}} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'accounts:editar' %}"><i class="fa fa-user"></i> Perfil</a></li>
                            <li><a href="#"><i class="fa fa-gear"></i> Configurações</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-power-off"></i> Log Out</a></li>                          
                        </ul>
                    </li>
                    
                    <li>
                        <form class="navbar-search">
                            <input type="text" placeholder="Search" class="form-control">
                        </form>
                    </li>
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </div>
</div>

    <!-- /#wrapper -->
    <script>
            (function($){
                $(function() {
                    {% block js %}
                    {% endblock %}
                    {% if messages %}
                        {% for message in messages %}
                            M.toast({html: '{{ message }}'});
                        {% endfor %}
                    {% endif %}
                });
            })(jQuery);
    </script>

    <script type="text/javascript">

        jQuery(function ($) {
            var performance = [12, 43, 34, 22, 12, 33, 4, 17, 22, 34, 54, 67],
                visits = [123, 323, 443, 32],
                traffic = [
                {
                    Source: "Direct", Amount: 323, Change: 53, Percent: 23, Target: 600
                },
                {
                    Source: "Refer", Amount: 345, Change: 34, Percent: 45, Target: 567
                },
                {
                    Source: "Social", Amount: 567, Change: 67, Percent: 23, Target: 456
                },
                {
                    Source: "Search", Amount: 234, Change: 23, Percent: 56, Target: 890
                },
                {
                    Source: "Internal", Amount: 111, Change: 78, Percent: 12, Target: 345
                }];


            $("#shieldui-chart1").shieldChart({
                theme: "dark",

                primaryHeader: {
                    text: "Visitors"
                },
                exportOptions: {
                    image: false,
                    print: false
                },
                dataSeries: [{
                    seriesType: "area",
                    collectionAlias: "Q Data",
                    data: performance
                }]
            });

            $("#shieldui-chart2").shieldChart({
                theme: "dark",
                primaryHeader: {
                    text: "Traffic Per week"
                },
                exportOptions: {
                    image: false,
                    print: false
                },
                dataSeries: [{
                    seriesType: "pie",
                    collectionAlias: "traffic",
                    data: visits
                }]
            });

            $("#shieldui-grid1").shieldGrid({
                dataSource: {
                    data: traffic
                },
                sorting: {
                    multiple: true
                },
                rowHover: false,
                paging: false,
                columns: [
                { field: "Source", width: "170px", title: "Source" },
                { field: "Amount", title: "Amount" },                
                { field: "Percent", title: "Percent", format: "{0} %" },
                { field: "Target", title: "Target" },
                ]
            });            
        });        
    </script>
</body>
</html>

defesa/core/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div id="page-wrapper">
        <div>
            <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Banca Pendente</h3>
                        </div>
                        <div>
                        <div class="panel-body">
                            <div >
                                  <table id="banca" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Título</th>
                                            <th>Autor</th>
                                            <th>Orientador</th>
                                            <th>Co-orientador</th>
                                            <th>Ações</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Título</th>
                                            <th>Autor</th>
                                            <th>Orientador</th>
                                            <th>Co-orientador</th>
                                            <th>Ações</th>
                                        </tr>
                                    </tfoot>
                                        <tbody>
                                        {% for trabalho in trabalhos %}
                                            <tr>
                                            <td>{{ trabalho.titulo }}</td>
                                            <td>{{ trabalho.autor }}</td>
                                            <td>{{ trabalho.orientador }}</td>
                                            <td>{{ trabalho.co_orientador }}</td>
                                            <td>
                                                <a href="{% url 'trabalhos:detalhe' trabalho.id %}"><i class="material-icons" style="color:black;">visibility</i></a>
                                                {% if user.id == trabalho.orientador.id %}
                                                    <a href="{% url 'trabalhos:editar' trabalho.id %}"><i class="material-icons" style="color:black;">create</i></a>
                                                    <a href="#"><i class="material-icons" style="color:black;">clear</i></a>
                                                {% endif %}
                                            </td>
                                        {% endfor %}
                                        </tr>
                                        </tbody>
                                </table>  
                            </div>
                        </div>
                    </div>
                    </div>

                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Agendamento Pendente</h3>
                        </div>
                        <div class="panel-body">
                            <div >
                                <table id="agenda" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Título</th>
                                            <th>Autor</th>
                                            <th>Orientador</th>
                                            <th>Banca</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                        <th>Título</th>
                                            <th>Autor</th>
                                            <th>Orientador</th>
                                            <th>Banca</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        <tr>
                                            <td>Tiger Nixon</td>
                                            <td>System Architect</td>
                                            <td>Edinburgh</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Garrett Winters</td>
                                            <td>Accountant</td>
                                            <td>Tokyo</td>
                                            <td>Ricardo Rios, Ivan Machado, Tatiane Rios</td>
                                        </tr>
                                         </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title"><i class="fa fa-bar-chart-o"></i> Defesas Confirmadas</h3>
                        </div>
                        <div class="panel-body">
                            <div >
                                <table id="confirmadas" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th>Título</th>
                                            <th>Autor</th>
                                            <th>Orientador</th>
                                            <th>Banca</th>
                                            <th>Data/Hora</th>
                                            <th>Local</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                        <th>Título</th>
                                            <th>Autor</th>
                                            <th>Orientador</th>
                                            <th>Banca</th>
                                            <th>Data/Hora</th>
                                            <th>Local</th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        <tr>
                                            <td>Tiger Nixon</td>
                                            <td>System Architect</td>
                                            <td>Edinburgh</td>
                                            <td>Ricardo Rios, Ivan Machado, Tatiane Rios</td>
                                            <td>30/01/18 as 14:00</td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Garrett Winters</td>
                                            <td>Accountant</td>
                                            <td>Tokyo</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Ashton Cox</td>
                                            <td>Junior Technical Author</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Cedric Kelly</td>
                                            <td>Senior Javascript Developer</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        <tr>
                                            <td>Airi Satou</td>
                                            <td>Accountant</td>
                                            <td>Tokyo</td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                         </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    
{% endblock %}