core/urls.py
from django.conf.urls import include, url
from . import  views


urlpatterns = [
    # Examples:
    url(r'^$', views.home, name='home'),
    url(r'^bancas_pendentes/$', views.banca_pendente, name='bancas_pendentes'),
    url(r'^agendamentos_pendentes/$', views.agendamento_pendente, name='agendamentos_pendentes'),
    url(r'^defesas_confirmadas/$', views.defesas_confirmadas, name='defesas_confirmadas'),
]

defesa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^trabalhos/', include('trabalhos.urls', namespace='trabalhos')),
    url(r'^email/', include('mensagem.urls', namespace='mensagem')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mensagem/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Examples:
    url(r'^(?P<pk>\d+)', views.EnviaEmailParticipacaoBanca.as_view(), name='email_participacao_banca'),
    url(r'^confirma-participacao-banca/(?P<key>\w+)/$', views.confirmada_participacao_banca, name='confirmada_participacao_banca'),
    url(r'^rejeita-participacao-banca/(?P<key>\w+)/$', views.rejeitada_participacao_banca, name='rejeitada_participacao_banca'),
]

trabalhos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Examples:
    url(r'^cadastrar-trabalho/novo$', views.cadastrar_trabalho, name='cadastrar_trabalho'),
    url(r'^detalhe/(?P<pk>\d+)/$', views.detalhe, name='detalhe'),
    url(r'^editar/(?P<pk>\d+)/$', views.TrabalhoUpdateView.as_view(), name='editar'),
    url(r'^(?P<pk>\d+)/$', views.TrabalhoDetail.as_view(), name='deletar'),
    url(r'^agendamento/novo/(?P<pk>\d+)/$', views.defesatrabalho, name='cadastrar_agendamento_defesa'),
    url(r'^banca-trabalho/(?P<pk>\d+)/$', views.banca_trabalho, name='banca_trabalho'),
    url(r'^deletar-agendamento/(?P<pk>\d+)/$', views.AgendamentoDetail.as_view(), name='deletar_agendamento'),
    url(r'^detalhe-agendamento/(?P<pk>\d+)/$', views.AgendamentoDetail.as_view(), name='detalhe_agendamento'),
]

mensagem/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import re

from django.db import models
from accounts.models import Usuario
from trabalhos.models import Trabalhos

# Create your models here.


class EmailParticipacaoBanca(models.Model):

    remetente = models.ForeignKey(Usuario, verbose_name='Usuarios', related_name='usuarios')
    destinatario = models.ForeignKey(Usuario,verbose_name='Usuario', related_name='usuario')
    trabalho = models.ForeignKey(Trabalhos, verbose_name='Trabalhos', related_name='trabalhos')
    key = models.CharField('Chave', max_length=100, unique=True)
    visualizada = models.DateField('Visualizada em', null=True, blank=True)
    tipo = models.CharField('Tipo', max_length=30)

mensagem/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.shortcuts import render

from core.mail import send_mail_template
from core.utils import generate_hash_key
from trabalhos.models import Trabalhos, DefesaTrabalho, BancaTrabalho
from .models import EmailParticipacaoBanca

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from datetime import date
from django.conf import  settings

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

# Create your views here.

class EnviaEmailParticipacaoBanca(APIView):

    def post(self, request, pk, format=None):
        trabalho = Trabalhos.objects.get(pk=pk)
        key = generate_hash_key(request.user.username)
        email_participacao_banca = EmailParticipacaoBanca(
            remetente=request.user,
            destinatario=trabalho.orientador,
            key=key,
            trabalho=trabalho,
            tipo='pedido de participação'
        )
        base_url = request.scheme + "://" + request.get_host()
        email_participacao_banca.save()
        template_name = 'mensagem/banca/pedido_participacao_banca.html'
        if (settings.DEV):
            subject = 'Convite para compor a banca avaliadora do trabalho ' + unicode(trabalho.titulo)
        else:
            subject = 'Convite para compor a banca avaliadora do trabalho ' + trabalho.titulo
        context = {'trabalho': trabalho, 'base_url': base_url, 'key': key, 'avaliador': request.user}
        send_mail_template(subject, template_name, context, [trabalho.orientador.email], request.user.email)
        return Response(status=status.HTTP_204_NO_CONTENT)

def confirmada_participacao_banca(request, key):

        participacao_banca = get_object_or_404(EmailParticipacaoBanca, key=key)

        if participacao_banca.visualizada:
            messages.error(request, 'Esta mensagem já foi respondida')
            return redirect('core:home')
        else:
            if participacao_banca.tipo == 'pedido de participação':
                banca = BancaTrabalho.objects.create(
                    usuario=participacao_banca.remetente,
                    trabalho=participacao_banca.trabalho,
                    status='aceito_pelo_orientador'
                )
                template_name = 'mensagem/banca/solicitacao_aceita.html'
                template_name_render = 'mensagem/banca/resposta_solicitacao.html'
                if (settings.DEV):
                    subject = 'Convite para compor a banca avaliadora do trabalho ' + unicode(participacao_banca.trabalho.titulo)
                else:
                    subject = 'Convite para compor a banca avaliadora do trabalho ' + participacao_banca.trabalho.titulo
                usuario = participacao_banca.remetente
            else:
                banca = BancaTrabalho.objects.filter(trabalho=participacao_banca.trabalho, usuario=participacao_banca.destinatario)
                if not banca:
                    banca = BancaTrabalho.objects.create(
                        usuario=participacao_banca.destinatario,
                        trabalho=participacao_banca.trabalho,
                        status='aceito_pelo_avaliador'
                    )
                else:
                    banca.update(status='aceito_pelo_avaliador')
                template_name = 'mensagem/banca/convite_aceito.html'
                template_name_render = 'mensagem/banca/resposta_convite.html'
                if (settings.DEV):
                    subject = 'Convite para compor a banca avaliadora do trabalho ' + unicode(participacao_banca.trabalho.titulo)
                else:
                    subject = 'Convite para compor a banca avaliadora do trabalho ' + participacao_banca.trabalho.titulo
                usuario = participacao_banca.destinatario

            base_url = request.scheme + "://" + request.get_host()

            #dispara email de resposta
            context = {'trabalho': participacao_banca.trabalho,
                       'usuario' : usuario,
                       'base_url': base_url}
            send_mail_template(
                subject,
                template_name,
                context,
                [participacao_banca.remetente.email]
            )
            participacao_banca.visualizada = date.today()
            participacao_banca.save()
            avaliadores = BancaTrabalho.objects.filter(trabalho=participacao_banca.trabalho).exclude(status__contains='negado')
            defesa = DefesaTrabalho.objects.filter(trabalho=participacao_banca.trabalho)

            if defesa and defesa[0].status == 'pendente_banca_avaliadora' and avaliadores.filter(status__contains='aceito').count() >= 3 :
                defesa.update(status='agendado')
                if (settings.DEV):
                    subject = 'Convite para compor a banca avaliadora do trabalho ' + unicode(defesa[0].trabalho.titulo)
                else:
                    subject = 'Convite para compor a banca avaliadora do trabalho ' + defesa[0].trabalho.titulo
                template_name = 'mensagem/banca/confirmado_agendamento_defesa.html'
                context = {'trabalho': defesa[0].trabalho, 'defesa': defesa[0], 'avaliadores': avaliadores}
                for avaliador in avaliadores:
                    send_mail_template(
                        subject,
                        template_name,
                        context,
                        [avaliador.usuario.email]
                    )

            return render(request, template_name_render)

def rejeitada_participacao_banca(request, key):

    participacao_banca = get_object_or_404(EmailParticipacaoBanca, key=key)

    #verifica se a mensagem já foi visualizada
    if participacao_banca.visualizada:
        messages.error(request, 'Esta mensagem já foi respondida')
        return render(request,'mensagem/banca/resposta_lida')
    else:
        #verifica se foi uma solicitação feita por algum professor ou aluno para participar da banca ou se foi
        # um convite do orientador a algum professou ou aluno para compor a banca
        if participacao_banca.tipo == 'pedido de participação':
            banca = BancaTrabalho(
                usuario=participacao_banca.remetente,
                trabalho=participacao_banca.trabalho,
            )
            banca.status = 'negado_pelo_orientador'
            template_name = 'mensagem/banca/solicitacao_rejeitado.html'
            template_name_render = 'mensagem/banca/resposta_solicitacao.html'
            if (settings.DEV):
                subject = 'Convite para compor a banca avaliadora do trabalho ' + unicode(participacao_banca.trabalho.titulo)
            else:
                subject = 'Convite para compor a banca avaliadora do trabalho ' + participacao_banca.trabalho.titulo
        else:
            banca = BancaTrabalho.objects.get(trabalho=participacao_banca.trabalho,
                                              usuario=participacao_banca.destinatario)
            banca.status = 'negado_pelo_avaliador'
            template_name = 'mensagem/banca/convite_rejeitado.html'
            template_name_render = 'mensagem/banca/resposta_convite.html'
            if (settings.DEV):
                subject = 'Convite para compor a banca avaliadora do trabalho ' + unicode(participacao_banca.trabalho.titulo)
            else:
                subject = 'Convite para compor a banca avaliadora do trabalho ' + participacao_banca.trabalho.titulo

        banca.save()
        base_url = request.scheme + "://" + request.get_host()
        # dispara email de resposta ao orientador ou ao professor/aluno informando que o pedido/convite foi rejeitado
        context = {'trabalho': participacao_banca.trabalho,
                   'usuario': participacao_banca.destinatario,
                   'base_url': base_url}
        send_mail_template(
            subject,
            template_name,
            context,
            [participacao_banca.remetente.email]
        )
        participacao_banca.visualizada = date.today()
        participacao_banca.save()
        return render(request, template_name_render)

mensagem/templates/mensagem/banca/confirmado_agendamento_defesa.html
<h3>Prezados,</h3>

<p>A defesa do trabalho {{ trabalho.titulo }} foi confirmada e abaixo segue as informações</p>
<p>Título: {{ trabalho.titulo }}</p>
<p>Autor: {{ trabalho.autor }}</p>
<p>Orientador: {{ trabalho.orientador }}</p>
<p>Local: {{ defesa.local }}</p>
<p>Data: {{ defesa.data }}</p>
<p>Hora: {{ defesa.hora }}</p>
<p>Banca Avaliadora:
    <ul>
        {% for avaliador in avaliadores %}
            <li>{{ avaliador.usuario.name }} </li>
        {% endfor %}
    </ul>
</p>

mensagem/templates/mensagem/banca/convite_aceito.html
<h3>Prezada(o), {{ trabalho.orientador.name }}</h3>
<p>
    O seu Convite para fazer parte da banca avaliadora do trabalho {{ trabalho.titulo }},
    foi aceita pelo(a) avaliador(a) {{ usuario.name }}.

</p>

mensagem/templates/mensagem/banca/convite_participacao_aceita.html
<h3>Prezada(o), {{ trabalho.orientador.name }}</h3>
<p>
    A seu Convite para fazer parte da banca avaliadora do trabalho {{ trabalho.titulo }},
    foi aceita pelo(a) avaliador(a) {{ usuario.name }}.

</p>

mensagem/templates/mensagem/banca/convite_participacao_banca.html
<h3></h3>
<p>
    {{ defesa.trabalho.orientador.name }} o convida para participar da banca avaliadora do trabalho
    {{defesa.trabalho.titulo }} , que sera realizada no {{defesa.local}}, no dia e hora {{defesa.data}}
    as {{ defesa.hora}}

</p>
<p>para aceitar ao convite click no link a baixo:</p>
<a href="{{ base_url }}{% url 'mensagem:confirmada_participacao_banca' key %}">Aceitar a solicitação</a>
<p>para recusar o convite click no link a baixo:</p>
<a href="{{ base_url }}{% url 'mensagem:rejeitada_participacao_banca' key %}">Rejeita a solicitação</a>

mensagem/templates/mensagem/banca/convite_rejeitado.html
<h3>Prezada(o), {{ trabalho.orientador.name }}</h3>
<p>
    O seu Convite para fazer parte da banca avaliadora do trabalho {{ trabalho.titulo }},
    foi recusado pelo(a) avaliador(a) {{ usuario.name }}.

</p>
<p>
    Caso deseje convidar outra pessoa clique no link abaixo:
</p>
<a href="{{ base_url }}{% url 'trabalhos:banca_trabalho' trabalho.id %}">Convidar uma nova pessoa</a>

mensagem/templates/mensagem/banca/pedido_participacao_banca.html
<h3>Prezado, {{ trabalho.orientador }},</h3>

<p>{{ avaliador.name }} solicita participar da banca avaliadora do trabalho {{ trabalho.titulo }}</p>

<p>para aceitar a solicição click no link a baixo:</p>
<a href="{{ base_url }}{% url 'mensagem:confirmada_participacao_banca' key %}">Aceitar a solicitação</a>

<p>para recusar a solicitação click no link a baixo:</p>
<a href="{{ base_url }}{% url 'mensagem:rejeitada_participacao_banca' key %}">Rejeita a solicitação</a>

mensagem/templates/mensagem/banca/resposta_convite.html
<!DOCTYPE html>

{% load static %}
{% load widget_tweaks %}
{% load material_form %}

<html lang="pt-br">
    <head>
        <meta charset="utf-8">

        <title>Defesas Ufba</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


        {% include 'material/includes/material_css.html' %}

        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'core/font-awesome/css/font-awesome.min.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/local.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/jquery.tagsinput.css' %}" />


    </head>
    <body>
        <main>
            <div class="container">
                <div id="page-wrapper">
                    <div class="center">
                        <img src="{% static 'accounts/images/Brasão_da_UFBA.png' %}" style="width: 120px;" alt="My image">
                    </div>
                    <div class="container">
                        <div class="col s12 m2 z-depth-2 grid">
                            <div class="center">
                                <h2>A sua resposta foi enviada ao orientador</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- /#wrapper -->
        <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        <script type="text/javascript" src="{% static 'core/js/jquery-1.10.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'core/js/local.js' %}"></script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="{% static 'material/js/jquery.js' %}"></script>
        {% include 'material/includes/material_js.html' %}
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
        <script type="text/javascript" src="{% static 'core/js/jquery.tagsinput.js' %}"></script>
    </body>
</html>

mensagem/templates/mensagem/banca/resposta_solicitacao.html
<!DOCTYPE html>

{% load static %}
{% load widget_tweaks %}
{% load material_form %}

<html lang="pt-br">
    <head>
        <meta charset="utf-8">

        <title>Defesas Ufba</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>


        {% include 'material/includes/material_css.html' %}

        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'core/font-awesome/css/font-awesome.min.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/local.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/jquery.tagsinput.css' %}" />


    </head>
    <body>
        <main>
            <div class="container">
                <div id="page-wrapper">
                    <div class="center">
                        <img src="{% static 'accounts/images/Brasão_da_UFBA.png' %}" style="width: 120px;" alt="My image">
                    </div>
                    <div class="container">
                        <div class="col s12 m2 z-depth-2 grid">
                            <div class="center">
                                <h2>A sua resposta foi enviada ao solicitante</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- /#wrapper -->
        <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        <script type="text/javascript" src="{% static 'core/js/jquery-1.10.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'core/js/local.js' %}"></script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="{% static 'material/js/jquery.js' %}"></script>
        {% include 'material/includes/material_js.html' %}
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
        <script type="text/javascript" src="{% static 'core/js/jquery.tagsinput.js' %}"></script>
    </body>
</html>

mensagem/templates/mensagem/banca/solicitacao_aceita.html
<h3>Prezada(o), {{ usuario.name }}</h3>
<p>
    A sua solicitação para fazer parte da banca avaliadora do trabalho {{ trabalho.titulo }},
    foi aceita pelo(a) orientador(a) {{ trabalho.orientador.name }}. Assim que o agendamento para a defesa do
    trabalho for confirmada você receberá um email informando o dia, a hora e o local.

</p>

mensagem/templates/mensagem/banca/solicitacao_participacao_aceita.html
<h3>Prezada(o), {{ usuario.name }}</h3>
<p>
    A sua solicitação para fazer parte da banca avaliadora do trabalho {{ trabalho.titulo }},
    foi aceita pelo(a) orientador(a) {{ trabalho.orientador.name }}. Assim que o agendamento para a defesa do
    trabalho for confirmada você receberá um email informando o dia, a hora e o local.

</p>

mensagem/templates/mensagem/banca/solicitacao_rejeitado.html
<h3>Prezada(o), {{ usuario.name }}</h3>
<p>
    A sua solicitação para fazer parte da banca avaliadora do trabalho {{ trabalho.titulo }},
    foi rejeitada pelo(a) orientador(a) {{ trabalho.orientador.name }}.
</p>