accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^entrar/$', views.meu_login, name='login'),
    url(r'^sair/$', auth_views.logout, {'next_page': 'accounts:login'}, name='logout'),
    url(r'^cadastro/$', views.cadastro, name='cadastro'),
    url(r'^cadastro/(?P<key>\w*)/$', views.cadastro, name='cadastro'),
    url(r'^cadastro/novo-perfil/$', views.PerfilCreateView.as_view(), name='novo_perfil'),
    url(r'^editar/(?P<pk>\d+)/$', views.UsuarioUpdateView.as_view(), name='editar'),
    url(r'^(?P<pk>\d+)/$', views.UsuarioUpdateApiView.as_view(), name='editar_api'),
    url(r'^editar-senha/$', views.editar_senha, name='editar_senha'),
    url(r'^nova-senha/$', views.reset_senha, name='reset_senha'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)/$', views.reset_senha_confirm, name='reset_senha_confirm'),
    url(r'^certificado/orientador/(?P<pk>\d+)/$', views.CertificadoOrientadorPDFView.as_view(), name='certificado_orientador'),
    url(r'^certificado/avaliador/(?P<pk>\d+)/(?P<user_id>\d+)/$', views.CertificadoAvaliadorPDFView.as_view(), name='certificado_avaliador'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

core/urls.py
from django.conf.urls import include, url
from . import  views


urlpatterns = [
    # Examples:
    url(r'^$', views.home, name='home'),
    url(r'^bancas_pendentes/$', views.banca_pendente, name='bancas_pendentes'),
    url(r'^agendamentos_pendentes/$', views.agendamento_pendente, name='agendamentos_pendentes'),
    url(r'^defesas_confirmadas/$', views.defesas_confirmadas, name='defesas_confirmadas'),
]

defesa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^trabalhos/', include('trabalhos.urls', namespace='trabalhos')),
    url(r'^email/', include('mensagem.urls', namespace='mensagem')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
# -*- coding: utf-8 -*-
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from core.mail import send_mail_template
from core.utils import generate_hash_key

from .models import NovaSenha, Titulo, Perfil

Usuario = get_user_model()


class LoginForm(forms.ModelForm):
	username = forms.CharField(label='Usuário', widget=forms.TextInput(attrs={'class':'form-control'}))
	password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={'class':'form-control'}))

	class Meta:
		model = Usuario
		fields = ['username', 'password1']

class CadastroForm(forms.ModelForm):
	username = forms.CharField(label='Usuário',widget=forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Usuário'}))
	name = forms.CharField(label='Nome',widget=forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Nome'}))
	titulo = forms.ModelChoiceField(
		label='Titulação', 
		queryset=Titulo.objects.order_by('descricao'), 
		widget=forms.Select(attrs={'class':'form-control form-control-user', 'placeholder':'Selecione'})
	)
	perfil = forms.ModelChoiceField(
		label='Perfil',
		queryset=Perfil.objects.exclude(descricao='Coordenador').order_by('descricao'),
		widget=forms.Select(attrs={'class': 'form-control form-control-user', 'placeholder': 'Selecione'})
	)
	email = forms.EmailField(label='E-mail', widget=forms.TextInput(attrs={'class':'form-control  form-control-user','placeholder':'E-mail'}))

	password1 = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'placeholder': 'Senha'}))

	password2 = forms.CharField(label='Confirmar senha', widget=forms.PasswordInput(attrs={'class':'form-control form-control-user','placeholder': 'Confirmar senha'}))
	# def clean_email(self):
	# 	email = self.cleaned_data['email']
	# 	if User.objects.filter(email=email).exists():kk
	# 		raise forms.ValidationError('Já existe usuario com este E-mail')
	# 	return email

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError('A confirmação não está correta')
		return password2	

	def save(self, commit=True):
		user = super(CadastroForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		user.titulo = self.cleaned_data['titulo']
		user.perfil = self.cleaned_data['perfil']
		if commit:
			user.save()
		return user	

	class Meta:
		model = Usuario
		fields = ['username', 'name', 'email']	


class EditaCadastroForm(forms.ModelForm):
	# titulo = forms.ModelChoiceField(
	# 	label='Titulação',
	# 	queryset=Titulo.objects.order_by('descricao'),
	# 	widget=forms.Select(attrs={'class': 'select-wrapper', 'placeholder': 'Selecione'})
	# )
	# def clean_email(self):
	# 	email = self.cleaned_data['email']
	# 	queryset = User.objects.filter(email=email).exclude(pk=self.instance.pk)
	# 	if queryset.exists():
	# 		raise forms.ValidationError('Já existe usuario com este E-mail')
	# 	return email


	class Meta:
		model = Usuario
		fields = ['titulo', 'name', 'email']


class ResetSenhaForm(forms.Form):

	email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class':'form-control form-control-user'}))

	def clean_email(self):
		email = self.cleaned_data['email']
		if Usuario.objects.filter(email=email).exists():
			return email
		raise forms.ValidationError('Nenhum usuário encontrado com este e-mail')

	def save(self):
		user = Usuario.objects.get(email=self.cleaned_data['email'])
		key = generate_hash_key(user.username)
		reset = NovaSenha(key=key, user=user)
		reset.save()
		base_url = self.scheme + "://" + self.get_host()
		template_name = 'accounts/reset_senha_mail.html'
		subject = 'Criar nova Senha no Defesas Ufba'
		context = { 'reset': reset, 'base_url': base_url}
		send_mail_template(subject, template_name, context, [user.email])

class PerfilForm(forms.ModelForm):
	
	class Meta:
		model = Perfil
		fields = [
			'descricao',
			'nivel_acesso',
		]

accounts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.conf import settings
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView
from accounts.decorators import acesso, valida_perfil
from django.contrib import messages
from datetime import date
from easy_pdf.views import PDFTemplateView
from core.mail import send_mail_template
from datetime import  date

from .serializers import UsuarioSerializer
from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework import generics

from core.utils import generate_hash_key

from .forms import CadastroForm, LoginForm, EditaCadastroForm, ResetSenhaForm, PerfilForm
from .models import NovaSenha, Perfil
from mensagem.models import  EmailParticipacaoBanca
from mensagem.views import confirmada_participacao_banca
from trabalhos.models import  Trabalhos, DefesaTrabalho, BancaTrabalho

Usuario = get_user_model()

# Create your views here.

def meu_login(request):
	template_name = 'accounts/login.html'
	form = LoginForm()
	context = {}
	if request.method == 'POST':
		user = authenticate(username=request.POST['username'], password=request.POST['password1'])
		if user is not None:
			login(request, user)
			return redirect('core:home')
		else:
			messages.error(request,'login ou senha incorretos')
	context = { 'form': form }
	
	return render(request, template_name, context)			


def cadastro(request, key=None):
	template_name = 'accounts/cadastro.html'

	if request.method == 'POST':
		form = CadastroForm(request.POST)
		if form.is_valid():
			user = form.save()
			if key:
				participacao_banca = get_object_or_404(EmailParticipacaoBanca, key=key)
				participacao_banca.destinatario = user
				participacao_banca.save()

				confirmada_participacao_banca(request, key)

			messages.success(request,'Usuário cadastrado com sucesso')
			return redirect('core:home')
	else:
		form = CadastroForm()		
	context = {
		'form': form
	}

	return render(request, template_name, context)

def reset_senha(request):

	form = ResetSenhaForm(request.POST or None)
	context = {}
	if form.is_valid():
		user = Usuario.objects.get(email=form.cleaned_data['email'])
		key = generate_hash_key(user.username)
		reset = NovaSenha(key=key, user=user)
		reset.save()
		base_url = request.scheme + "://" + request.get_host()
		template_name = 'accounts/reset_senha_mail.html'
		subject = 'Criar nova Senha no Defesas Ufba'
		context = { 'reset': reset, 'base_url': base_url}
		send_mail_template(subject, template_name, context, [user.email])
		context['success'] = True

		return redirect('accounts:login')

	template_name = 'accounts/reset_senha.html'
	context['form'] = form
	return render(request, template_name, context)


def reset_senha_confirm(request, key):
	template_name = 'accounts/reset_senha_confirm.html'
	context = {}
	reset = get_object_or_404(NovaSenha, key=key)
	form = SetPasswordForm(user=reset.user, data=request.POST or None)
	if form.is_valid():
		form.save()
		context['success'] = True
		messages.success(request,'Usuário cadastrado com sucesso')
		return redirect('accounts:login')
	context['form'] = form	

	return render(request, template_name, context)	



class UsuarioUpdateView(UpdateView):
	template_name = 'accounts/editar.html'
	model = Usuario
	form_class = EditaCadastroForm


	def form_valid(self, form):
		messages.success(self.request, ("Perfil atualizado com sucesso"))
		return super(UsuarioUpdateView, self).form_valid(form)

	def get_success_url(self):
		return reverse("accounts:editar", kwargs={'pk': self.get_object().id})


class UsuarioUpdateApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Usuario.objects.all()
    serializer_class = UsuarioSerializer


@login_required
def editar_senha(request):
	template_name = 'accounts/editar_senha.html'
	context = {}

	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			context['success'] = True
	else:
		form = PasswordChangeForm(user=request.user)

	context['form'] = form
	return render(request, template_name, context)


class PerfilCreateView(CreateView):
	template_name = 'accounts/novo_perfil.html'
	model = Perfil
	form_class = PerfilForm
	success_url = reverse_lazy(
		"accounts:lista_perfis"
	)

	@method_decorator(login_required)
	@method_decorator(acesso('alto'))
	def dispatch(self, *args, **kwargs):
		return super(PerfilCreateView, self).dispatch(*args, **kwargs)




class CertificadoOrientadorPDFView(PDFTemplateView):
	template_name = 'accounts/certificado_orientador.html'
	base_url = 'file://' + settings.STATIC_ROOT
	download_filename = 'certificado.pdf'

	def get_context_data(self, pk, **kwargs):
		trabalho = Trabalhos.objects.get(pk=pk)
		defesa = DefesaTrabalho.objects.get(trabalho=trabalho)
		return super(CertificadoOrientadorPDFView, self).get_context_data(
			pagesize='A4',
			title='Certificado',
			trabalho=trabalho,
			defesa=defesa,
			data=date.today(),
			**kwargs
		)

class CertificadoAvaliadorPDFView(PDFTemplateView):
	template_name = 'accounts/certificado_avaliador.html'
	base_url = 'file://' + settings.STATIC_ROOT
	download_filename = 'certificado.pdf'

	def get_context_data(self, pk, user_id, **kwargs):
		trabalho = Trabalhos.objects.get(pk=pk)
		avaliador = BancaTrabalho.objects.get(trabalho=trabalho, usuario_id=user_id)
		defesa = DefesaTrabalho.objects.get(trabalho=trabalho)
		return super(CertificadoAvaliadorPDFView, self).get_context_data(
			pagesize='A4',
			title='Certificado',
			trabalho=trabalho,
			defesa=defesa,
			data=date.today(),
			avaliador=avaliador,
			**kwargs
		)

def teste(request):
	template_name = 'accounts/teste.html'
	return  render(request, template_name)

defesa/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.conf import settings
from django.views.generic import CreateView
from defesa.accounts.decorators import acesso, valida_perfil

from defesa.core.utils import generate_hash_key

from .forms import CadastroForm, LoginForm, EditaCadastroForm, ResetSenhaForm, PerfilForm
from .models import NovaSenha, Perfil

Usuario = get_user_model()

# Create your views here.

def meu_login(request):
	template_name = 'accounts/login.html'
	form = LoginForm()
	context = {}
	if request.method == 'POST':
		user = authenticate(username=request.POST['username'], password=request.POST['password1'])
		if user is not None:
			login(request, user)
			return redirect('core:home')
	else:
		context['insuccess'] = True
	context = { 'form': form }
	
	return render(request, template_name, context)			

@login_required
@acesso('alto')
def cadastro(request):
	template_name = 'accounts/cadastro.html'

	if request.method == 'POST':
		form = CadastroForm(request.POST)
		if form.is_valid():
			user = form.save()
			user = authenticate(username=user.username, password=form.cleaned_data['password1'])
			login(request, user)
			return redirect('core:home')
	else:
		form = CadastroForm()		
	context = {
		'form': form
	}

	return render(request, template_name, context)

def reset_senha(request):
	template_name = 'accounts/reset_senha.html'
	form = ResetSenhaForm(request.POST or None)
	context = {}
	if form.is_valid():
		form.save()
		context['success'] = True
	context['form'] = form
	return render(request, template_name, context)


def reset_senha_confirm(request, key):
	template_name = 'accounts/reset_senha_confirm.html'
	context = {}
	reset = get_object_or_404(NovaSenha, key=key)
	form = SetPasswordForm(user=reset.user, data=request.POST or None)
	if form.is_valid():
		form.save()
		context['success'] = True
	context['form'] = form	
	return render(request, template_name, context)	


@login_required
def editar(request):
	template_name = 'accounts/editar.html'
	context = {}
	if request.method == 'POST':
		form = EditaCadastroForm(request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			form = EditaCadastroForm(instance=request.user)
			context['success'] = True
	else:
		form = EditaCadastroForm(instance=request.user)

	context['form'] = form
	
	return render(request, template_name, context)

@login_required
def editar_senha(request):
	template_name = 'accounts/editar_senha.html'
	context = {}

	if request.POST == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			context['success'] = True
	else:
		form = PasswordChangeForm(user=request.user)

	context['form'] = form
	return render(request, template_name, context)



class PerfilCreateView(CreateView):
	template_name = 'accounts/novo_perfil.html'
	model = Perfil
	form_class = PerfilForm
	success_url = reverse_lazy(
		"accounts:lista_perfis"
	)
	@method_decorator(login_required)
	@method_decorator(acesso('alto'))
	def dispatch(self, *args, **kwargs):
		return super(PerfilCreateView, self).dispatch(*args, **kwargs)

accounts/templates/accounts/cadastro.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="pt-br">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Cadastro - Finis</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/admin.css' %}" />

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Cadastro - Finis</h1>
              </div>
              <form class="user" method="post">
                {% csrf_token %}
                <div class="form-group row">
                {% for field in form %}
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <label class="mylabel">{{ field.label }}</label>
                        {{ field }}
                        <br />
                    </div>
                    <br />
                {% endfor %}
                </div>
                
                <button type="submit" class="btn btn-primary btn-user btn-block">Cadastrar</button>
                <hr>
             
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="{% url 'accounts:login' %}">Já tem cadastro? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

accounts/templates/accounts/certificado_avaliador.html
{% extends "easy_pdf/base.html" %}
{% load static %}
{% block extra_style %}
<style type="text/css">
    body {
        font-family: "Helvetica", "sans-serif";
        color: #333333;
    }

    .cabecalho {
        font-size: 20px;
    }

    .endereco {
        margin-bottom: 0px;
        margin-top: -12px;
    }
</style>
{% endblock %}

{% block content %}
<div id="content">
    <div class="row">
        <div class="col-md-4">
            <img src="{% static 'accounts/images/Brasão_da_UFBA.png' %}" alt="My image">
        </div>
        <div class="col-md-8">
            <h1 align="center">
                MINIST&EacuteRIO DA EDUCA&Ccedil&AtildeO
                <br>
                UNIVERSIDADE FEDERAL DA BAHIA
                <br>
                INSTITUTO DE MATEM&AacuteTICA E ESTAT&IacuteSTICA
                <br>
                Av. Ademar de Barros s/n - Campus Universit&aacuterio de Ondina - Salvador Bahia
                <br>
                CEP 40170-101 Tel: (071) 3283-6340/6341/6337 Fax: 3283-6336
            </h1>
        </div>
        <br><br><br><br>
        <br><br><br><br>
        <br><br><br><br>

        <div class="col-md-12" style="font-size: 20px;" align="center">
            <b>DECLARA&Ccedil&AtildeO</b>
        </div>
        <div class="col-md-12">
            <p style="font-size: 14px;">
                Declaro, para os devidos fins, que o professor(a) {{ avaliador.usuario.name }} participou como
                membro da Banca de Avalia&ccedil&atildeo do Projeto Final de {{ trabalho.autor }},
                aluno(a) do curso de Bacharelado em Ci&ecirccia da Computa&ccedil&atildeo da UFBA, intitulado
                {{ trabalho.titulo }}, apresentado no {{ defesa.data }}, no Instituto
                de Matem&aacutetica e Estat&iacutestica da UFBA.

            </p>
        </div>

        <br><br><br><br>
        <br><br><br><br>
        <br><br><br><br>

        <div class="col-md-8">
            <h1 align="center">
                Salvador, {{ data }}.
            </h1>

            <br><br><br>
            <br><br><br>

            <h1 align="center">
                Coordenador do Curso de Bacharelado
                <br>
                em Ci&ecircncias da Computa&ccedil&atildeo
                <br>
                UFBA
            </h1>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/editar.html
{% extends 'core/base.html' %}

{% load material_form %}
{% block content %}

<div id="page-wrapper">
    <h3 class="titulo-box">Editar Perfil</h3>
    <div style="padding: 15px;" class="col s12 m2 z-depth-2">
        <div class="container">
            <form method="post">
                {% csrf_token %}
                {% form form=form %}{% endform %}
                <div class="bt-box">
                    <button type="submit" class="btn green btn-success">Salvar</button>
                    <a class="waves-effect waves-light blue btn" href="{% url 'core:home' %}">Voltar</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
{% load material_form %}
<html lang="pt-br">

<head>
  {% include 'material/includes/material_css.html' %}  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Defesas Ufba</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/jquery.tagsinput.css' %}" />
  <!-- Custom styles for this template-->
  <link rel="stylesheet" type="text/css" href="{% static 'core/css/admin.css' %}" />
</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9"> <!-- pra reduzir <div class="col-md-6"> -->
      <!--<div class="col-md-6"> -->  
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-md-1"></div>
              <div class="col-md-5 d-none d-lg-block">
                <br /><br />
                <img  src="/static/accounts/images/Brasão_da_UFBA.png" width="300"/>
              </div> 
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">FINIS - UFBA!</h1>
                  </div>
                  <form class="user" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" id="id_username" name="username" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="id_password1" name="password1" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Lembrar dados</label>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">Login</button>
                    <hr>
                   
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'accounts:reset_senha' %}">Esqueceu sua senha?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'accounts:cadastro' %}">Cadastro</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>
  <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script type="text/javascript" src="{% static 'core/js/jquery-1.10.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'core/js/local.js' %}"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
    <script type="text/javascript" src="{% static 'core/js/jquery.tagsinput.js' %}"></script>
    
</body>

</html>

accounts/templates/accounts/reset_senha_mail.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

</head>

<body>
    <h3>Email de Recuperação de senha</h3>
    <p>Prezada(o), {{ reset.user.name }}</p>
    <p>

        Para criar uma nova senha por favor
        <a href="{{ base_url }}{% url 'accounts:reset_senha_confirm' reset.key %}">clique aqui!</a>
        Caso não tenha solicitado a recuperação de senha, favor desconsiderar este email.
    </p>
    <!--<div class="row">-->
    <!--<div class="col s12 m6">-->
    <!--<div class="card blue-grey darken-1">-->
    <!--<div class="card-content white-text">-->
    <!--<span class="card-title">Card Title</span>-->
    <!--<p>I am a very simple card. I am good at containing small bits of information.-->
    <!--I am convenient because I require little markup to use effectively.</p>-->
    <!--</div>-->
    <!--<div class="card-action">-->
    <!--<a href="#">This is a link</a>-->
    <!--<a href="#">This is a link</a>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!--</div>-->
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>