accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    url(r'^entrar/$', views.meu_login, name='login'),
    url(r'^sair/$', auth_views.logout, {'next_page': 'accounts:login'}, name='logout'),
    url(r'^cadastro/$', views.cadastro, name='cadastro'),
    url(r'^cadastro/(?P<key>\w*)/$', views.cadastro, name='cadastro'),
    url(r'^cadastro/novo-perfil/$', views.PerfilCreateView.as_view(), name='novo_perfil'),
    url(r'^editar/(?P<pk>\d+)/$', views.UsuarioUpdateView.as_view(), name='editar'),
    url(r'^(?P<pk>\d+)/$', views.UsuarioUpdateApiView.as_view(), name='editar_api'),
    url(r'^editar-senha/$', views.editar_senha, name='editar_senha'),
    url(r'^nova-senha/$', views.reset_senha, name='reset_senha'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)/$', views.reset_senha_confirm, name='reset_senha_confirm'),
    url(r'^certificado/orientador/(?P<pk>\d+)/$', views.CertificadoOrientadorPDFView.as_view(), name='certificado_orientador'),
    url(r'^certificado/avaliador/(?P<pk>\d+)/(?P<user_id>\d+)/$', views.CertificadoAvaliadorPDFView.as_view(), name='certificado_avaliador'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

core/urls.py
from django.conf.urls import include, url
from . import  views


urlpatterns = [
    # Examples:
    url(r'^$', views.home, name='home'),
    url(r'^bancas_pendentes/$', views.banca_pendente, name='bancas_pendentes'),
    url(r'^agendamentos_pendentes/$', views.agendamento_pendente, name='agendamentos_pendentes'),
    url(r'^defesas_confirmadas/$', views.defesas_confirmadas, name='defesas_confirmadas'),
]

defesa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^', include('core.urls', namespace='core')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^trabalhos/', include('trabalhos.urls', namespace='trabalhos')),
    url(r'^email/', include('mensagem.urls', namespace='mensagem')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trabalhos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Examples:
    url(r'^cadastrar-trabalho/novo$', views.cadastrar_trabalho, name='cadastrar_trabalho'),
    url(r'^detalhe/(?P<pk>\d+)/$', views.detalhe, name='detalhe'),
    url(r'^editar/(?P<pk>\d+)/$', views.TrabalhoUpdateView.as_view(), name='editar'),
    url(r'^(?P<pk>\d+)/$', views.TrabalhoDetail.as_view(), name='deletar'),
    url(r'^agendamento/novo/(?P<pk>\d+)/$', views.defesatrabalho, name='cadastrar_agendamento_defesa'),
    url(r'^banca-trabalho/(?P<pk>\d+)/$', views.banca_trabalho, name='banca_trabalho'),
    url(r'^deletar-agendamento/(?P<pk>\d+)/$', views.AgendamentoDetail.as_view(), name='deletar_agendamento'),
    url(r'^detalhe-agendamento/(?P<pk>\d+)/$', views.AgendamentoDetail.as_view(), name='detalhe_agendamento'),
]

core/models.py
from django.db import models
# Create your models here.

class Teste(models.Model):
    teste = models.CharField('Teste', max_length=30)


    class Meta:
        verbose_name = 'Teste'
        verbose_name_plural = 'Teste'

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from trabalhos.models import Trabalhos, DefesaTrabalho

@login_required
def home(request):
	template_nameHome = 'core/home.html'
	return render(request, template_nameHome)

def banca_pendente(request):
	trabalhos = Trabalhos.objects.all().filter(defesatrabalho__isnull=True)
	defesas = DefesaTrabalho.objects.all()
	list = []
	for defesa in defesas:
		avaliadores = defesa.trabalho.banca.all().exclude(bancatrabalho__status__contains='negado')
		lista = []
		for avaliador in avaliadores:
			lista.append(avaliador.name)

		defesas_dic = {
			'id': defesa.id,
			'local': defesa.local,
			'data': defesa.data,
			'hora': defesa.hora,
			'trabalho': defesa.trabalho,
			'banca': lista,
			'status': defesa.status,
		}
		list.append(defesas_dic)
		contextBanca = {"trabalhos": trabalhos, "defesas": list}
		template_nameBanca = 'core/banca_pendente.html'
	return  render(request, template_nameBanca, contextBanca)

def agendamento_pendente(request):
	trabalhos = Trabalhos.objects.all().filter(defesatrabalho__isnull=True)
	defesas = DefesaTrabalho.objects.all()
	list = []
	for defesa in defesas:
		avaliadores = defesa.trabalho.banca.all().exclude(bancatrabalho__status__contains='negado')
		lista = []
		for avaliador in avaliadores:
			lista.append(avaliador.name)

		defesas_dic = {
			'id': defesa.id,
			'local': defesa.local,
			'data': defesa.data,
			'hora': defesa.hora,
			'trabalho': defesa.trabalho,
			'banca': lista,
			'status': defesa.status,
		}
		list.append(defesas_dic)
		contextAgendamento = {"trabalhos": trabalhos, "defesas": list}
		template_nameAgendamento = 'core/agendamento_pendente.html'
	return  render(request, template_nameAgendamento, contextAgendamento)

def defesas_confirmadas(request):
	trabalhos = Trabalhos.objects.all().filter(defesatrabalho__isnull=True)
	defesas = DefesaTrabalho.objects.all()
	list = []
	for defesa in defesas:
		avaliadores = defesa.trabalho.banca.all().exclude(bancatrabalho__status__contains='negado')
		lista = []
		for avaliador in avaliadores:
			lista.append(avaliador.name)

		defesas_dic = {
			'id': defesa.id,
			'local': defesa.local,
			'data': defesa.data,
			'hora': defesa.hora,
			'trabalho': defesa.trabalho,
			'banca': lista,
			'status': defesa.status,
		}
		list.append(defesas_dic)
		contextDefesas = {"trabalhos": trabalhos, "defesas": list}
		template_nameDefesa = 'core/defesas_confirmadas.html'
	return  render(request, template_nameDefesa, contextDefesas)

defesa/core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from defesa.trabalhos.models import Trabalhos

@login_required
def home(request):
	trabalhos = Trabalhos.objects.all()
	template_name = 'home.html'
	context = {"trabalhos": trabalhos}
	return render(request, template_name, context)

core/templates/core/base.html
<!DOCTYPE html>

{% load static %}
{% load widget_tweaks %}

<html lang="pt-br">
    <head>
        <meta charset="utf-8">

        <title>Defesas Ufba</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        {{ form.media.css }}

        {% include 'material/includes/material_css.html' %}

        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-lite/1.1.0/material.min.css">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.material.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'core/font-awesome/css/font-awesome.min.css' %}" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/local.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'core/css/jquery.tagsinput.css' %}" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />

        {% csrf_token %}

    </head>
    <body>
        <div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
            <header  class="demo-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
                <div class="mdl-layout__header-row">
                    <a href="{% url 'core:home' %}">
                        <span class="mdl-layout-title">Home</span>
                    </a>
                    <div class="mdl-layout-spacer"></div>
                </div>
            </header>
            {% if request.user.is_authenticated %}
            {% include 'core/sidebar.html' %}
            {% endif %}

            <main class="mdl-layout__content mdl-color--white-100">
            {% block container %}
                <div id="content" class="container">
                    {% endblock %}
                    {% block content %}
                    {% endblock %}
                </div>
            </main>

        </div>


        <!-- /#wrapper -->
        <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        <script type="text/javascript" src="{% static 'core/js/jquery-1.10.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'core/js/local.js' %}"></script>
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="{% static 'material/js/jquery.js' %}"></script>
        {% include 'material/includes/material_js.html' %}
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>
        <script type="text/javascript" src="{% static 'core/js/jquery.tagsinput.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
        <script>
            (function($){
                $(".dropdown-trigger").dropdown();
                $(function() {
                    {% block js %}
                    {% endblock %}
                    {% if messages %}
                        {% for message in messages %}
                            M.toast({html: '{{ message }}'});
                        {% endfor %}
                    {% endif %}
                });

            })(jQuery);
        </script>
    {{ form.media.js }}
    </body>
</html>

core/templates/core/sidebar.html
{% load staticfiles %}

<!-- Sidebar -->
<div class=" mdl-layout__drawer mdl-color--gray-100">
    <header class="demo-drawer-header light-blue">
        <img src="{% static 'core/images/usuario-login.png' %}" class="center circle" id="foto-perfil-sidebar">
        <div class="white-text center">
            <span>{{ user.name }}</span>
        </div>
    </header>
    <nav class="demo-navigation indent mdl-color--grey-100 mdl-color-text--grey-600">
        {% if user.perfil.descricao == 'Coordenador' %}
            {% include 'core/sidebar_menu_coordenador.html' %}
        {% endif %}
        {% if user.perfil.descricao == 'Professor'%}
            {% include 'core/sidebar_menu_professor.html' %}
        {% endif %}
        <a class="mdl-navigation__link mdl-color-text--blue-grey" href="{% url 'accounts:editar' user.id %}">
            <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation"></i>Editar Perfil</a>
        <a class="mdl-navigation__link mdl-color-text--blue-grey" href="{% url 'accounts:editar_senha' %}">
            <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation"></i> Alterar Senha</a>
        <a class="mdl-navigation__link mdl-color-text--blue-grey" href="{% url 'accounts:logout' %}">
            <i class="mdl-color-text--blue-grey-400 material-icons" role="presentation"></i>Sair
        </a>
    </nav>
</div>
<!-- /#sidebar-wrapper -->

core/templates/core/sidebar_menu_coordenador.html
{% load staticfiles %}

<a class="mdl-navigation__link mdl-color-text--blue-grey" href="{% url 'accounts:cadastro' %}">
    <i class="mdl-color-text--blue-grey-400 material-icons"></i>Cadastrar Usuário
</a>
<!--<a class="mdl-navigation__link mdl-color-text&#45;&#45;blue-grey" href="{% url 'accounts:novo_perfil' %}">-->
    <!--<i class="mdl-color-text&#45;&#45;blue-grey-400 material-icons"></i>Cadastrar Tipo Perfil-->
<!--</a>-->

core/templates/core/sidebar_menu_professor.html
{% load staticfiles %}

<a class="mdl-navigation__link mdl-color-text--blue-grey" href="{% url 'trabalhos:cadastrar_trabalho'%}">
    <i class="mdl-color-text--blue-grey-400 material-icons"></i>Cadastrar TCC
</a>